### ISSUE TITLE
astropy_helpers todo list

### ISSUE THREAD

**Issue by embray** [embray/astropy#5]
For my own use, a todo list on `astropy_helpers` based on the last telecon discussion on the topic:
- [x] Move Sphinx extensions from `astropy` to `astropy_helpers`
- [x] Add `--offline` flag recognized by `ah_bootstrap` to force disabling of downloads
- [x] When going to download from the internet, issue a warning message informing the user of the `--offline` option
- [ ] ~~Add a custom `sdist` and extension to `bdist` commands to include `astropy_helpers` in distributions (it would not be included by default)~~
- [x] In cases where astropy-helpers was bundled with a source distribution, add the option to automatically use a newer (compatible) version of astropy-helpers than the bundled one if available (this way bug fixes can be pushed out, etc.)
- [x] Add `setup.py test` command to `astropy_helpers`, but with the provision that it requires `astropy` itself to be installed in order to fully function
- [x] Per the APE draft, a `_compiler` module template should be provided.
- [x] Discussion the rationale for the above points in the APE
