### ISSUE TITLE
modeling todo list

### ISSUE THREAD

**Issue by embray** [embray/astropy#8]
A list of things I would like to update in the modeling package
- [ ] As mentioned in astropy/astropy#2235 parameter constraints should actually fix the allowed initial and update values for parameters
- [ ] Relatedly, all types of models should be allowed to have constraints on their parameters, even if they are not "fittable" models
- [ ] As a use case for that, some of the current "validation" done on some of the projection models' parameters would be implemented as constraints.  For example on the cylindrical projections the relationship between lambda and mu could be implemented as a tied constraint rather than awkward use of `setters`.
- [ ] Remove `getter`/`setter` methods for parameters. I think it's too confusing that we would display parameters with one value, but use a different value for them internally.  Currently this is used only for converting inputs in degrees to radians (for use in trig functions.  But once we have proper support for `Quantity` this particular use case will go away, and so there will be no _in practice_ use for `getter`/`setter` at all and they can just be removed.
- [ ] Consider including as part of model definitions details about what inputs and outputs a model receives, a la how parameters are specified.  Currently we just specify an n_input and n_output, but some models really require more information on how different inputs and/or outputs should be formatted.  It might also be helpful for documentation formatting and for passing information to fitters.  For example some fitters currently hard-code a lot of special cases for polynomial models (see `LinearLSQFitter._map_domain_window for example`).  Adding rules for input/output variables on the models themselves might help alleviate the need for special cases.
